### PR TITLE
Convert data types to Immutable.js

### PR DESCRIPTION
**Pull request by nicholastmosher**
This change is due to the fact that our querying logic requires the nice O(1) set lookup property that Immutable's data types provide. The Set from javascript's standard libraries does not provide hash methods or high performance lookups, which is causing performance problems.

Since we're making use of Immutable.js's data types anyways, this PR takes it all the way, turning all of our declared data types into Immutable.js Records, which give a very rich API for interacting with and manipulating the data, as well as strong guarantees about immutability, which makes reasoning about the code much easier.

### CODE REVIEW

**Comment by jshearer** [comment]
Testing locally...

**Comment by jshearer** [comment]
reading data sure does take longer

**Comment by jshearer** [comment]
Hitting the initial page in the frontend causes

```
TypeError: Cannot read property 'size' of undefined
    at /Users/js/Documents/School/Senior_Project/backend/src/services/v1.ts:116:80
    at /Users/js/Documents/School/Senior_Project/backend/node_modules/immutable/dist/immutable.js:5268:29
    at /Users/js/Documents/School/Senior_Project/backend/node_modules/immutable/dist/immutable.js:1117:18
    at ArraySeq.__iterate (/Users/js/Documents/School/Senior_Project/backend/node_modules/immutable/dist/immutable.js:458:13)
    at FromEntriesSequence.__iterate (/Users/js/Documents/School/Senior_Project/backend/node_modules/immutable/dist/immutable.js:1111:25)
    at reduce (/Users/js/Documents/School/Senior_Project/backend/node_modules/immutable/dist/immutable.js:5263:16)
    at FromEntriesSequence.reduce$1 [as reduce] (/Users/js/Documents/School/Senior_Project/backend/node_modules/immutable/dist/immutable.js:4783:14)
    at V1Service.get_wgs (/Users/js/Documents/School/Senior_Project/backend/src/services/v1.ts:112:8)
    at ServiceInvoker.<anonymous> (/Users/js/Documents/School/Senior_Project/backend/node_modules/typescript-rest/src/server/service-invoker.ts:72:31)
    at step (/Users/js/Documents/School/Senior_Project/backend/node_modules/typescript-rest/dist/server/service-invoker.js:32:23)
```

Exporting genes gives

```
TypeError: Cannot read property 'gene' of undefined
    at /Users/js/Documents/School/Senior_Project/backend/src/export.ts:79:67
    at Array.map (<anonymous>)
    at Object.genesToCSV (/Users/js/Documents/School/Senior_Project/backend/src/export.ts:79:52)
    at V1Service.genes (/Users/js/Documents/School/Senior_Project/backend/src/services/v1.ts:90:31)
    at ServiceInvoker.<anonymous> (/Users/js/Documents/School/Senior_Project/backend/node_modules/typescript-rest/src/server/service-invoker.ts:72:31)
    at step (/Users/js/Documents/School/Senior_Project/backend/node_modules/typescript-rest/dist/server/service-invoker.js:32:23)
    at Object.next (/Users/js/Documents/School/Senior_Project/backend/node_modules/typescript-rest/dist/server/service-invoker.js:13:53)
    at /Users/js/Documents/School/Senior_Project/backend/node_modules/typescript-rest/dist/server/service-invoker.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/js/Documents/School/Senior_Project/backend/node_modules/typescript-rest/dist/server/service-invoker.js:3:12)
```

**Comment by nicholastmosher** [comment]
I believe I fixed the `size is undefined` error already. I'll take a look at the second one

**Pull request merged**
