### PR TITLE
Write GAF file Exporting!

### PR DESCRIPTION
**Pull request by jshearer**

### CODE REVIEW

**Comment by nicholastmosher** [comment]
I tried downloading some data and this is a sample of what I got which I don't think is entirely correct yet:

```
!segments: 
!gaf-version: 2.0
"=""TAIR""","=""locus:2043067""","=""ENOC""","=""""","=""GO:0000015""","=""TAIR:AnalysisReference:501756966""","=""IEA""","=""InterPro:IPR000941""","=""C""","=""AT2G29560""","=""AT2G29560|ENOC|ENO3|cytosolic enolase|enolase 3|F16P2.6|F16P2_6""","=""protein""","=""""","=""20190408""","=""InterPro""","=""""","=""TAIR:locus:2043067"""
"=""TAIR""","=""locus:2044851""","=""LOS2""","=""""","=""GO:0000015""","=""TAIR:AnalysisReference:501756966""","=""IEA""","=""InterPro:IPR000941""","=""C""","=""AT2G36530""","=""AT2G36530|LOS2|ENO2|LOW EXPRESSION OF OSMOTICALLY RESPONSIVE GENES 2|enolase 2|F1O11.16|F1O11_16""","=""protein""","=""""","=""20190408""","=""InterPro""","=""""","=""TAIR:locus:2044851"""
"=""TAIR""","=""locus:2032970""","=""AT1G25260""","=""""","=""GO:0000027""","=""TAIR:AnalysisReference:501756966""","=""IEA""","=""InterPro:IPR033867""","=""P""","=""AT1G25260""","=""AT1G25260|F4F7.35|F4F7_35""","=""protein""","=""""","=""20190404""","=""InterPro""","=""""","=""TAIR:locus:2032970"""
"=""TAIR""","=""locus:2017963""","=""TUN""","=""""","=""GO:0000030""","=""TAIR:AnalysisReference:501756966""","=""IEA""","=""InterPro:IPR026051""","=""F""","=""AT1G16570""","=""AT1G16570|TUN|TURAN|F19K19.11|F19K19_11""","=""protein""","=""""","=""20190907""","=""InterPro""","=""""","=""TAIR:locus:2017963"""
"=""TAIR""","=""locus:2011962""","=""ALATS""","=""""","=""GO:0000049""","=""TAIR:AnalysisReference:501756968""","=""IEA""","=""UniProtKB-KW:KW-0820""","=""F""","=""AT1G50200""","=""AT1G50200|ALATS|ACD|Alanyl-tRNA synthetase|F14I3.17|F14I3_17|ALARS""","=""protein""","=""""","=""20190327""","=""UniProt""","=""""","=""TAIR:locus:2011962"""
"=""TAIR""","=""locus:2064821""","=""CTEXP""","=""""","=""GO:0000049""","=""TAIR:Publication:501746929""","=""IDA""","=""""","=""F""","=""AT2G40730""","=""AT2G40730|CTEXP|cytoplasmic tRNA export protein|T7D17.9|T7D17_9""","=""protein""","=""""","=""20120106""","=""TAIR""","=""""","=""TAIR:locus:2064821"""
"=""TAIR""","=""locus:2074552""","=""TRM1a""","=""""","=""GO:0000049""","=""TAIR:AnalysisReference:501756968""","=""IEA""","=""UniProtKB-KW:KW-0820""","=""F""","=""AT3G02320""","=""AT3G02320|TRM1a|AtTRM1a|tRNA methyltransferase 1a|F11A12.1|F11A12_1""","=""protein""","=""""","=""20190907""","=""UniProt""","=""""","=""TAIR:locus:2074552"""
"=""TAIR""","=""locus:2085455""","=""AT3G58140""","=""""","=""GO:0000049""","=""TAIR:AnalysisReference:501756966""","=""IEA""","=""InterPro:IPR002319""","=""F""","=""AT3G58140""","=""AT3G58140|F9D24.50""","=""protein""","=""""","=""20190907""","=""InterPro""","=""""","=""TAIR:locus:2085455"""
```

It seems that a) the segments metadata is not yet filled out, and b) that there is a lot of crazy quoting going on here. I'd like to see us fix that before we merge this.

**Comment by nicholastmosher** [comment]
I have a commit coming in just a minute that changes the query parameters introduced here. Instead of using `asGAF` and `asGeneCSV`, there will just be one new parameter called `format` whose values can be `gaf`, `gene-csv`, or `json`, with `json` being the default. Incoming soon.

**Comment by jshearer** [comment]
```
!gaf-version: 2.0
!filters: C-UNKNOWN
"","locus:2079747","","","GO:0000003","TAIR:Communication:501741973","IBA","PANTHER:PTN000495591|WB:WBGene00002998","P","AT3G05380","AT3G05380|ALY2|ATALY2|ALWAYS EARLY 2|ARABIDOPSIS THALIANA ALWAYS EARLY 2|F22F7.18|F22F7_18","protein","","20180615","GOC","",""
"","locus:2089438","","","GO:0000003","TAIR:Communication:501741973","IBA","PANTHER:PTN000495591|WB:WBGene00002998","P","AT3G21430","AT3G21430|ATALY3|ALY3|ARABIDOPSIS THALIANA ALWAYS EARLY 3|ALWAYS EARLY 3","protein","","20180615","GOC","",""
"","locus:2143666","","","GO:0000003","TAIR:Communication:501741973","IBA","PANTHER:PTN000495591|WB:WBGene00002998","P","AT5G27610","AT5G27610|ATALY1|ALY1|ARABIDOPSIS THALIANA ALWAYS EARLY 1|ALWAYS EARLY 1|F15A18.70|F15A18_70","protein","","20180615","GOC","",""
"","locus:2179122","","","GO:0000012","TAIR:Communication:501741973","IBA","PANTHER:PTN000281062|MGI:MGI:1913658|UniProtKB:Q7Z2E3","P","AT5G01310","AT5G01310|APTX|APRATAXIN-like|T10O8.20|T10O8_20","protein","","20180803","GOC","",""
"","locus:2150931","","","GO:0000012","TAIR:Communication:501741973","IBA","PANTHER:PTN000275870|MGI:MGI:1920036|UniProtKB:Q9NUW8","P","AT5G15170","AT5G15170|TDP1|tyrosyl-DNA phosphodiesterase 1|F8M21.60|F8M21_60","protein","","20180803","GOC","",""
"","locus:2202114","","","GO:0000014","TAIR:Communication:501741973","IBA","PANTHER:PTN002107734|TAIR:locus:2202114","F","AT1G11190","AT1G11190|BFN1|ENDO1|bifunctional nuclease i|ENDONUCLEASE 1|T28P6.14|T28P6_14","protein","","20180615","GOC","",""
"","locus:2045437","","","GO:0000014","TAIR:Communication:501741973","IBA","PANTHER:PTN000429848|UniProtKB:Q92878","F","AT2G31970","AT2G31970|RAD50|ATRAD50|F22D22.28|F22D22_28|dna repair-recombination protein","protein","","20180630","GOC","",""
```

Woohoo!

**Comment by nicholastmosher** [comment]
@jshearer the GAF file format does not include any quotes around fields. Are we able to remove those?

This is an example snippet straight from the `tair.gaf` file

```
DB	DB Object ID	DB Object Symbol	Qualifier	GO ID	DB:Reference (JDB:Reference)	Evidence Code	With (or) From	Aspect	DB Object Name	DB Object Type	Taxon	Date	Assigned By	Annotation Extension	Gene Product Form ID
TAIR	locus:2031476	ENO1		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT1G74030	AT1G74030|ENO1|enolase 1|F2P9.10|F2P9_10	protein	taxon:3702	20190907	InterPro		TAIR:locus:2031476
TAIR	locus:2043067	ENOC		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT2G29560	AT2G29560|ENOC|ENO3|cytosolic enolase|enolase 3|F16P2.6|F16P2_6	protein	taxon:3702	20190408	InterPro		TAIR:locus:2043067
```

**Comment by nicholastmosher** [comment]
Ok, I think this is ready to go in order to deploy for demo today. Some things to keep in the mind for future work:

* We should capture the header names from the original GAF file and restore it exactly on the exported file.

* We may want to consider exporting the "filters" metadata as a query string which can be copy and pasted into the URL for a new request.

* Some fields in some columns have double-quotes that were stripped off by the parser which are not restored upon export. Here's a sample diff of the original file and the exported file. Notice the column with the "cytochrome" string in it.

```diff
21493c21493
< TAIR	locus:2027407	CYP71A18		GO:0005576	TAIR:AnalysisReference:501780126	ISM		C	"cytochrome P450, family 71, subfamily A, polypeptide 18"	AT1G11610|AT1G11610.2	protein	taxon:3702	20180831	TAIR		TAIR:gene:6530296126
---
> TAIR	locus:2027407	CYP71A18		GO:0005576	TAIR:AnalysisReference:501780126	ISM		C	cytochrome P450, family 71, subfamily A, polypeptide 18	AT1G11610|AT1G11610.2	protein	taxon:3702	20180831	TAIR		TAIR:gene:6530296126
21594c21594
< TAIR	locus:2013159	CYP722A1		GO:0005576	TAIR:AnalysisReference:501780126	ISM		C	"cytochrome P450, family 722, subfamily A, polypeptide 1"	AT1G19630|AT1G19630.1|F14P1.4|F14P1_4	protein	taxon:3702	20180831	TAIR		TAIR:gene:2013158
---
> TAIR	locus:2013159	CYP722A1		GO:0005576	TAIR:AnalysisReference:501780126	ISM		C	cytochrome P450, family 722, subfamily A, polypeptide 1	AT1G19630|AT1G19630.1|F14P1.4|F14P1_4	protein	taxon:3702	20180831	TAIR		TAIR:gene:2013158
21725c21725
< TAIR	locus:2032564	CYP705A24		GO:0005576	TAIR:AnalysisReference:501780126	ISM		C	"cytochrome P450, family 705, subfamily A, polypeptide 24"	AT1G28430|AT1G28430.1|F3M18.13|F3M18_13	protein	taxon:3702	20180831	TAIR		TAIR:gene:2032563
```

**Pull request merged**
